import React from 'react'

export default function Disclaimer() {
  return (
    <div className="disclaimer-box">
      <div className="disclaimer-title">
        ⚠️ Research Support Only
      </div>
      <div>
        Responses generated by this tool are for research purposes only and do not constitute medical advice.
        Always consult qualified healthcare professionals for medical decisions.
      </div>
    </div>
  )
}
