import logging
from typing import List, Dict, Any, Optional, TypedDict
from openai import OpenAI
from langgraph.graph import StateGraph, END
from app.config import settings
from app.services.embeddings import search_similar

logger = logging.getLogger(__name__)

DISCLAIMER = (
    "DISCLAIMER: Responses generated by this tool are for research support purposes only "
    "and do not constitute medical advice. Always consult qualified healthcare professionals "
    "for medical decisions."
)

class RAGState(TypedDict):
    question: str
    filters: Optional[Dict[str, Any]]
    chunks: List[Dict[str, Any]]
    answer: str
    sources: List[Dict[str, Any]]

def retrieve_node(state: RAGState) -> RAGState:
    chunks = search_similar(
        query=state["question"],
        n_results=8,
        filters=state.get("filters"),
    )
    return {**state, "chunks": chunks}

def _format_author_year(meta: dict) -> str:
    """Format as 'Smith et al., 2024' or 'Smith & Jones, 2024'."""
    authors_raw = meta.get("authors", "")
    authors = authors_raw.split(", ") if authors_raw else []
    pub_date = meta.get("pub_date", "")
    year = pub_date[:4] if pub_date and len(pub_date) >= 4 else "n.d."
    if not authors:
        return year
    first_last = authors[0].split(",")[0].strip() if "," in authors[0] else authors[0].split()[-1]
    if len(authors) == 1:
        return f"{first_last}, {year}"
    elif len(authors) == 2:
        second_last = authors[1].split(",")[0].strip() if "," in authors[1] else authors[1].split()[-1]
        return f"{first_last} & {second_last}, {year}"
    else:
        return f"{first_last} et al., {year}"


def generate_node(state: RAGState) -> RAGState:
    chunks = state["chunks"]
    if not chunks:
        return {**state, "answer": "No relevant literature found for this query. Please index relevant articles first using the Search & Index tab.", "sources": []}

    context_parts = []
    sources_map = {}
    ref_index = {}  # pmid -> reference number
    ref_counter = 1

    for chunk in chunks:
        meta = chunk["metadata"]
        pmid = meta.get("pmid", "")
        if pmid and pmid not in sources_map:
            author_year = _format_author_year(meta)
            sources_map[pmid] = {
                "pmid": pmid,
                "pmcid": meta.get("pmcid", ""),
                "doi": meta.get("doi", ""),
                "title": meta.get("title", ""),
                "journal": meta.get("journal", ""),
                "pub_date": meta.get("pub_date", ""),
                "authors": authors_raw.split(", ") if (authors_raw := meta.get("authors", "")) else [],
                "author_year": author_year,
                "ref_num": ref_counter,
            }
            ref_index[pmid] = ref_counter
            ref_counter += 1

    for pmid, src in sources_map.items():
        context_parts.append(
            f"[{src['ref_num']}] {src['author_year']} — {src['title']}\n"
            f"Journal: {src['journal']} | PMID: {pmid} | DOI: {src.get('doi', 'N/A')}\n"
        )

    # Add chunk content grouped by reference
    chunk_parts = []
    for chunk in chunks:
        pmid = chunk["metadata"].get("pmid", "")
        ref_num = ref_index.get(pmid, "?")
        chunk_parts.append(f"[{ref_num}] {chunk['content']}")

    context = "\n\n".join(chunk_parts)
    references_list = "\n".join(context_parts)

    system_prompt = (
        "You are a scientific literature assistant specializing in rare disease research. "
        "Write your answer as flowing, readable prose — like a knowledgeable colleague explaining the topic. "
        "Use natural language paragraphs, not bullet points. "
        "Cite sources inline using author-year style, e.g. (Smith et al., 2024) or numbered style [1], "
        "matching the reference numbers provided. Use citations naturally within sentences. "
        "Only use information from the provided excerpts. "
        "If the excerpts lack sufficient information, say so briefly and suggest searching for more specific articles.\n\n"
        f"Available references:\n{references_list}"
    )

    client = OpenAI(api_key=settings.OPENAI_API_KEY)
    try:
        response = client.chat.completions.create(
            model=settings.OPENAI_MODEL_ANSWER,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": f"Research excerpts:\n{context}\n\nQuestion: {state['question']}"},
            ],
            temperature=0.1,
            max_tokens=1500,
        )
        answer = response.choices[0].message.content
    except Exception as e:
        logger.error(f"OpenAI generation failed: {e}")
        answer = f"Error generating answer: {e}"

    return {**state, "answer": answer, "sources": list(sources_map.values())}

def build_rag_graph():
    graph = StateGraph(RAGState)
    graph.add_node("retrieve", retrieve_node)
    graph.add_node("generate", generate_node)
    graph.set_entry_point("retrieve")
    graph.add_edge("retrieve", "generate")
    graph.add_edge("generate", END)
    return graph.compile()

_rag_app = None

def get_rag_app():
    global _rag_app
    if _rag_app is None:
        _rag_app = build_rag_graph()
    return _rag_app

def run_rag(question: str, filters: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    app = get_rag_app()
    result = app.invoke({"question": question, "filters": filters, "chunks": [], "answer": "", "sources": []})
    return {
        "answer": result["answer"],
        "disclaimer": DISCLAIMER,
        "sources": result["sources"],
    }
