import logging
from typing import List, Dict, Any, Optional, TypedDict
from openai import OpenAI
from langgraph.graph import StateGraph, END
from app.config import settings
from app.services.embeddings import search_similar

logger = logging.getLogger(__name__)

DISCLAIMER = (
    "DISCLAIMER: Responses generated by this tool are for research support purposes only "
    "and do not constitute medical advice. Always consult qualified healthcare professionals "
    "for medical decisions."
)

class RAGState(TypedDict):
    question: str
    filters: Optional[Dict[str, Any]]
    chunks: List[Dict[str, Any]]
    answer: str
    sources: List[Dict[str, Any]]

def retrieve_node(state: RAGState) -> RAGState:
    chunks = search_similar(
        query=state["question"],
        n_results=8,
        filters=state.get("filters"),
    )
    return {**state, "chunks": chunks}

def generate_node(state: RAGState) -> RAGState:
    chunks = state["chunks"]
    if not chunks:
        return {**state, "answer": "No relevant literature found for this query. Please index relevant articles first using the Search & Index tab.", "sources": []}

    context_parts = []
    sources_map = {}
    for i, chunk in enumerate(chunks):
        meta = chunk["metadata"]
        pmid = meta.get("pmid", "")
        context_parts.append(
            f"[{i+1}] PMID: {pmid} | Title: {meta.get('title', '')} | "
            f"Journal: {meta.get('journal', '')} | Date: {meta.get('pub_date', '')}\n"
            f"{chunk['content']}"
        )
        if pmid and pmid not in sources_map:
            sources_map[pmid] = {
                "pmid": pmid,
                "pmcid": meta.get("pmcid", ""),
                "doi": meta.get("doi", ""),
                "title": meta.get("title", ""),
                "journal": meta.get("journal", ""),
                "pub_date": meta.get("pub_date", ""),
                "authors": meta.get("authors", "").split(", ") if meta.get("authors") else [],
            }

    context = "\n\n---\n\n".join(context_parts)
    system_prompt = (
        "You are a scientific literature assistant specializing in rare disease research. "
        "Answer the question based ONLY on the provided research excerpts. "
        "Cite sources using [PMID: X | Title: Y | DOI: Z] format after each relevant statement. "
        "Be concise and precise. If the excerpts don't contain enough information, say so clearly.\n\n"
        f"DISCLAIMER: {DISCLAIMER}"
    )

    client = OpenAI(api_key=settings.OPENAI_API_KEY)
    try:
        response = client.chat.completions.create(
            model=settings.OPENAI_MODEL_ANSWER,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": f"Research excerpts:\n{context}\n\nQuestion: {state['question']}"},
            ],
            temperature=0.1,
            max_tokens=1500,
        )
        answer = response.choices[0].message.content
    except Exception as e:
        logger.error(f"OpenAI generation failed: {e}")
        answer = f"Error generating answer: {e}"

    return {**state, "answer": answer, "sources": list(sources_map.values())}

def build_rag_graph():
    graph = StateGraph(RAGState)
    graph.add_node("retrieve", retrieve_node)
    graph.add_node("generate", generate_node)
    graph.set_entry_point("retrieve")
    graph.add_edge("retrieve", "generate")
    graph.add_edge("generate", END)
    return graph.compile()

_rag_app = None

def get_rag_app():
    global _rag_app
    if _rag_app is None:
        _rag_app = build_rag_graph()
    return _rag_app

def run_rag(question: str, filters: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    app = get_rag_app()
    result = app.invoke({"question": question, "filters": filters, "chunks": [], "answer": "", "sources": []})
    return {
        "answer": result["answer"],
        "disclaimer": DISCLAIMER,
        "sources": result["sources"],
    }
