import logging
from typing import List, Dict, Any, Optional

import anthropic

from app.config import settings
from app.services.embeddings import search_similar

logger = logging.getLogger(__name__)

DISCLAIMER = (
    "DISCLAIMER: Responses generated by this tool are for research support purposes only "
    "and do not constitute medical advice. Always consult qualified healthcare professionals "
    "for medical decisions."
)

SYSTEM_PROMPT = """You are a scientific literature assistant helping researchers explore rare disease literature.
Based ONLY on the provided research excerpts below, answer the question concisely and accurately with citations.

IMPORTANT RULES:
1. Only use information from the provided excerpts - do not use prior knowledge.
2. Cite sources using the format: [PMID: {pmid} | Title: {title} | DOI: {doi}]
3. If the excerpts do not contain enough information, say so clearly.
4. DISCLAIMER: This is for research support only and is not medical advice.

Research Excerpts:
{context}
"""


def _build_context(chunks: List[Dict[str, Any]]) -> str:
    parts = []
    for i, chunk in enumerate(chunks, 1):
        meta = chunk.get("metadata", {})
        pmid = meta.get("pmid", "N/A")
        title = meta.get("title", "N/A")
        doi = meta.get("doi", "N/A")
        journal = meta.get("journal", "N/A")
        authors = meta.get("authors", "")
        pub_date = meta.get("pub_date", "N/A")
        content = chunk.get("content", "")

        header = f"[Excerpt {i}] PMID: {pmid} | Title: {title} | DOI: {doi} | Journal: {journal} | Date: {pub_date}"
        parts.append(f"{header}\n{content}")

    return "\n\n---\n\n".join(parts)


def _extract_cited_sources(chunks: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Deduplicate sources by PMID."""
    seen = set()
    sources = []
    for chunk in chunks:
        meta = chunk.get("metadata", {})
        pmid = meta.get("pmid")
        if pmid and pmid not in seen:
            seen.add(pmid)
            authors_raw = meta.get("authors", "")
            if isinstance(authors_raw, str):
                authors = [a.strip() for a in authors_raw.split(",") if a.strip()] if authors_raw else []
            else:
                authors = authors_raw or []
            sources.append({
                "pmid": pmid,
                "pmcid": meta.get("pmcid"),
                "doi": meta.get("doi"),
                "title": meta.get("title", "N/A"),
                "journal": meta.get("journal"),
                "pub_date": meta.get("pub_date"),
                "authors": authors,
            })
    return sources


def retrieve_and_generate(
    question: str,
    filters: Optional[Dict[str, Any]] = None,
    top_k: int = 8,
) -> Dict[str, Any]:
    """
    RAG pipeline: retrieve relevant chunks then generate answer.
    Returns { answer, disclaimer, sources }
    """
    # Retrieve
    chunks = search_similar(question, n_results=top_k, filters=filters)

    if not chunks:
        return {
            "answer": "No relevant literature was found in the indexed database. Please search and index relevant articles first.",
            "disclaimer": DISCLAIMER,
            "sources": [],
        }

    # Build context
    context = _build_context(chunks)
    system = SYSTEM_PROMPT.replace("{context}", context)

    # Generate with Claude
    client = anthropic.Anthropic(api_key=settings.ANTHROPIC_API_KEY)

    try:
        message = client.messages.create(
            model="claude-opus-4-5",
            max_tokens=1500,
            system=system,
            messages=[
                {"role": "user", "content": question}
            ],
        )
        answer = message.content[0].text
    except Exception as e:
        logger.error(f"Claude API error: {e}")
        answer = f"Error generating answer: {str(e)}"

    sources = _extract_cited_sources(chunks)

    return {
        "answer": answer,
        "disclaimer": DISCLAIMER,
        "sources": sources,
    }
